# Setup
title:            QNICE-FPGA
tagline:          '16-bit System-on-a-Chip'
description:      '16-bit System-on-a-Chip for learning, teaching and having fun.'

author:
  name:           'sy2002'
  url:            http://www.sy2002.de

# Custom vars
version:          1.5

github:
  repo:           https://github.com/sy2002/QNICE-FPGA
